version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://localhost:27017/mydatabase

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
